apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.ports.port }}
      protocol: {{ .Values.service.ports.protocol }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}